from . import api

def validate_build_changeset() -> None: ...
def validate_source_changeset() -> None: ...

def build_options_path(pkg: api.Ident, prefix: str = None) -> str: ...
def build_script_path(pkg: api.Ident, prefix: str = None) -> str: ...
def build_spec_path(pkg: api.Ident, prefix: str = None) -> str: ...
def source_package_path(pkg: api.Ident, prefix: str = None) -> str: ...
