from typing import Sequence
from . import api, solve

def format_ident(pkg: api.Ident) -> str: ...
def format_build(build: str) -> str: ...
def format_options(options: api.OptionMap) -> str: ...
def format_request(name: str, requests: Sequence[api.Request]) -> str: ...
def format_solution(solution: solve.Solution, verbosity: int = 0) -> str: ...
