from . import api, SpFSRepository


def local_repository() -> SpFSRepository: ...
def remote_repository(path: str) -> SpFSRepository: ...
def open_tar_repository(path: str, create: bool = False) -> SpFSRepository: ...
