[package]
authors = { workspace = true }
edition = { workspace = true }
name = "parsedbuf"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
once_cell = { workspace = true }
paste = "1.0"
lasso = { workspace = true }
