[package]
name = "lint_proc_macro"
version = { workspace = true }
edition = { workspace = true }

[lib]
proc-macro = true

[dependencies]
ngrammatic = "0.4.0"
syn = "2.0"
quote = "1.0"
indicatif = { workspace = true }
