[package]
authors = { workspace = true }
edition = { workspace = true }
name = "spk-solve-solution"
version = { workspace = true }
license-file = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
description = { workspace = true }

[lints]
workspace = true

[features]
migration-to-components = [
    "spk-schema/migration-to-components",
    "spk-storage/migration-to-components",
]

[dependencies]
colored = { workspace = true }
console = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true, features = ["derive"] }
spfs = { workspace = true }
spk-schema = { workspace = true }
spk-storage = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
miette = { workspace = true }
