[package]
authors = ["Ryan Bottriell <rbottriell@imageworks.com>"]
edition = { workspace = true }
name = "spk-solve-solution"
version = { workspace = true }

[dependencies]
colored = { workspace = true }
console =  { workspace = true }
spfs = { version = '0.34.6', path = "../../../spfs" }
spk-schema = { path = "../../../spk-schema" }
spk-storage = { path = "../../../spk-storage" }
thiserror = { workspace = true }
