[package]
name = "sudoku"
authors.workspace = true
edition.workspace = true
version.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
description.workspace = true

[dependencies]

[lints]
workspace = true
