version: 0.44.0
release_notes: |
  - convert api module to rust
  - update to latest spfs
  - update build scripts to use bash instead of sh

toolchain:
  - kind: Rust
    toolchain: 1.87.0
    additional_toolchains:
      - nightly
  - kind: Shell
    variables:
      SENTRY_ENVIRONMENT: development
      SENTRY_DSN: http://4506b47108ac4b648fdf18a8d803f403@sentry.spimageworks.com/25
      SENTRY_USERNAME_OVERRIDE_VAR: GITLAB_USER_LOGIN
      PATH: $SPDEV_ENV/bin:$PATH

components:
  - kind: RustCrate
    name: spk
    ci_config:
      parallel: true
      tags:
        - proxy
      variables:
        FEATURES: migration-to-components,sentry,spfs/protobuf-src,legacy-spk-version-tags

  - kind: RustCrate
    name: spk-no-sentry
    ci_config:
      parallel: true
      tags:
        - proxy
      variables:
        FEATURES: migration-to-components,spfs/protobuf-src,legacy-spk-version-tags

  - kind: HugoDocs
    name: docs
    location: docs
    ci_config:
      parallel: true

  - kind: RPMPackage
    name: rpm
    spec_file: .site/spi/spk.spec
    ci_config:
      parallel: true
      tags:
        - docker
        - proxy

  - name: spfs-integration-tests
    kind: GenericBash
    test:
      - export CENTOS_IMAGE=docker-local.artifactory.spimageworks.com/gitlab/spi/dev/infrastructure/api/docker/spi-centos/centos-7.9.2009
      - docker pull $CENTOS_IMAGE
      # Do not use `--net host` so that spfs-monitor will not use cnproc,
      # it doesn't work in a container.
      - docker run --privileged --rm
        -v $PWD/dist/rpm/RPMS/x86_64:/tmp/rpms
        -v $PWD/.site/spi:/site
        -v $PWD/crates/spfs/tests/integration:/tests
        $CENTOS_IMAGE
        bash -xc "yum install -y sudo tcsh /tmp/rpms/*.rpm && /site/run_integration_tests.sh"
    ci_config:
      parallel: true
      needs:
        - component: rpm
          artifacts: true
      tags:
        - docker

  - kind: SentryRelease
    name: sentry
    project: spk
    deploy:
      enabled: true
    ci_config:
      parallel: true
      needs:
        - component: rpm

  - kind: WordpressReleaseNotes
    name: wp-release
    email:
      sender:
        name: SPK Team
    ci_config:
      parallel: true
      needs:
        - component: rpm

ci_config:
  all:
    variables:
      SPDEV_CONFIG_FILE: .site/spi/.spdev.yaml
  deploy:
    rules:
      - if: "$CI_COMMIT_BRANCH =~ /^spi-release-.*/"
        when: manual
  promote:
    rules:
      - if: "$CI_COMMIT_BRANCH =~ /^spi-release-.*/"
        when: manual
