baseURL = "https://spkenv.dev/"
languageCode = "en-us"
title = "SPK - Software Packaging System"

[params]
editUrl = "https://github.com/spkenv/spk/tree/main/docs/"
disableLandingPage = false
showVisitedLinks = false
themeVariant = "blue"

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe = true # for raw html

[module]
[[module.mounts]]
source = 'static'
target = 'assets/static'
[[module.mounts]]
source = '../docs/'
target = 'content'
