name: Python

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo pip3 install pipenv
      - run: pipenv sync --dev
      - name: Lint Formatting with Black
        run: pipenv run -- black --check
      - name: Lint Typing with MyPy
        run: pipenv run -- mypy spk
  test:
    runs-on: ubuntu-18.04
    steps:
      # essentially the goal is to run 'spfs run - -- pytest'
      # but we need to install spfs, have the spfs source code,
      # get the pipenv setup and then run this from within the pipenv...
      # all in the right version of a centos container
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # to work with tests
      - name: Download Deps
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.SPFS_PULL_PASSWORD}}
          workflow: rpm.yml
          workflow_conclusion: success
          branch: master
          name: Binary RPM
          path: deps
          repo: imageworks/spfs
      - name: Run Unit Tests
        env:
          SPFS_PULL_USERNAME: ${{ secrets.SPFS_PULL_USERNAME }}
          SPFS_PULL_PASSWORD: ${{ secrets.SPFS_PULL_PASSWORD }}
        run: docker run
          -e SPFS_PULL_USERNAME
          -e SPFS_PULL_PASSWORD
          -e HOME=/root
          --rm
          --privileged
          -v $PWD:/source
          centos:7 bash -ex /source/.github/scripts/unittests.sh
